services:
  langflow:
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://${HARBOR_LANGFLOW_DB_USER:-postgres}:${HARBOR_LANGFLOW_DB_PASSWORD:-password}@${HARBOR_CONTAINER_PREFIX}.langflow-db:5432/${HARBOR_LANGFLOW_DB_NAME:-langflow}
    depends_on:
      langflow-db:
        condition: service_healthy
    networks:
      - harbor_net

networks:
  harbor_net:
    external: true

# compose.x.langflow.redis.yml
services:
  langflow:
    environment:
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_CACHE_HOST=${HARBOR_CONTAINER_PREFIX}.langflow-redis
      - LANGFLOW_CACHE_PORT=6379
      - LANGFLOW_CACHE_PASSWORD=${HARBOR_LANGFLOW_REDIS_PASSWORD:-langflow123456}
    depends_on:
      langflow-redis:
        condition: service_healthy
    networks:
      - harbor_net

networks:
  harbor_net:
    external: true
