services:
  ldr:
    build:
      context: https://github.com/LearningCircuit/local-deep-research.git
      dockerfile: Dockerfile
    container_name: ${HARBOR_CONTAINER_PREFIX}.ldr
    ports:
      - ${HARBOR_LDR_HOST_PORT}:5000
    env_file:
      - ./.env
      - ./ldr/override.env
    environment:
      - OPENAI_API_KEY=${HARBOR_OPENAI_KEY}
      - LDR_OPENAI_API_KEY=${HARBOR_OPENAI_KEY}
      - ANTHROPIC_API_KEY=${HARBOR_ANTHROPIC_KEY}
      - LDR_ANTHROPIC_API_KEY=${HARBOR_ANTHROPIC_KEY}
    volumes:
      - ${HARBOR_LDR_WORKSPACE}:/home/ldrs/data
    networks:
      - harbor-network
